// <auto-generated />
using System;
using CompanyManagement.Entity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CompanyManagement.Entity.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260831104219_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CompanyManagement.Entity.Company", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("CompanyOwnerEmail")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("CompanyOwnerTelephoneNumber")
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.Property<int>("CompanyTypeId")
                        .HasColumnType("int");

                    b.HasKey("CompanyId");

                    b.HasIndex("CompanyTypeId");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("CompanyManagement.Entity.CompanyGivesBonusToEmployee", b =>
                {
                    b.Property<int>("CompanyGivesBonusToEmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CompanyGivesBonusToEmployeeDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("CompanyGivesBonusToEmployeeQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.HasKey("CompanyGivesBonusToEmployeeId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("CompanyGivesBonusToEmployees");
                });

            modelBuilder.Entity("CompanyManagement.Entity.CompanyHasDepartmentType", b =>
                {
                    b.Property<int>("CompanyHasDepartmentTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentTypeId")
                        .HasColumnType("int");

                    b.HasKey("CompanyHasDepartmentTypeId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("DepartmentTypeId");

                    b.ToTable("CompanyHasDepartmentTypes");
                });

            modelBuilder.Entity("CompanyManagement.Entity.CompanyHasProductOrService", b =>
                {
                    b.Property<int>("CompanyHasProductOrServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("CompanyHasProductOrServicePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CompanyHasProductOrServiceQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int>("ProductOrServiceId")
                        .HasColumnType("int");

                    b.HasKey("CompanyHasProductOrServiceId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ProductOrServiceId");

                    b.ToTable("CompanyHasProductOrServices");
                });

            modelBuilder.Entity("CompanyManagement.Entity.CompanyOwner", b =>
                {
                    b.Property<int>("CompanyOwnerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CompanyOwnerBirthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("CompanyOwnerEmail")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("CompanyOwnerIdentityNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.Property<string>("CompanyOwnerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("CompanyOwnerSurname")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("CompanyOwnerTelephoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.HasKey("CompanyOwnerId");

                    b.ToTable("CompanyOwners");
                });

            modelBuilder.Entity("CompanyManagement.Entity.CompanyOwnerHasCompany", b =>
                {
                    b.Property<int>("CompanyOwnerHasCompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int>("CompanyOwnerId")
                        .HasColumnType("int");

                    b.Property<int>("CompanyOwnerPercent")
                        .HasColumnType("int");

                    b.HasKey("CompanyOwnerHasCompanyId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CompanyOwnerId");

                    b.ToTable("CompanyOwnerHasCompanies");
                });

            modelBuilder.Entity("CompanyManagement.Entity.CompanyType", b =>
                {
                    b.Property<int>("CompanyTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.HasKey("CompanyTypeId");

                    b.ToTable("CompanyTypes");
                });

            modelBuilder.Entity("CompanyManagement.Entity.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CustomerEmail")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("CustomerSurname")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("CustomerTelephoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("CompanyManagement.Entity.CustomerBuysCompanyHasProductOrService", b =>
                {
                    b.Property<int>("CustomerBuysCompanyHasProductOrServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CompanyHasProductOrServiceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CustomerBuysCompanyHasProductOrServiceDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("CustomerBuysCompanyHasProductOrServiceQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("PaymentTypeId")
                        .HasColumnType("int");

                    b.HasKey("CustomerBuysCompanyHasProductOrServiceId");

                    b.HasIndex("CompanyHasProductOrServiceId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PaymentTypeId");

                    b.ToTable("CustomerBuysCompanyHasProductOrServices");
                });

            modelBuilder.Entity("CompanyManagement.Entity.DepartmentType", b =>
                {
                    b.Property<int>("DepartmentTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("DepartmentTypeId");

                    b.ToTable("DepartmentTypes");
                });

            modelBuilder.Entity("CompanyManagement.Entity.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EmployeeAddress")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<DateTime>("EmployeeBirthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmployeeEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("EmployeeIdentityNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<int>("EmployeeProfessionTypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("EmployeeSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("EmployeeSurname")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("EmployeeTelephoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.Property<int>("EmployeeYearsSpent")
                        .HasColumnType("int");

                    b.HasKey("EmployeeId");

                    b.HasIndex("EmployeeProfessionTypeId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("CompanyManagement.Entity.EmployeeHasCompanyHasDepartmentType", b =>
                {
                    b.Property<int>("EmployeeHasCompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CompanyHasDepartmentTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.HasKey("EmployeeHasCompanyId");

                    b.HasIndex("CompanyHasDepartmentTypeId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmployeeHasCompanyHasDepartmentTypes");
                });

            modelBuilder.Entity("CompanyManagement.Entity.Meeting", b =>
                {
                    b.Property<int>("MeetingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("MeetingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MeetingDetail")
                        .HasColumnType("nvarchar(1000)")
                        .HasMaxLength(1000);

                    b.Property<string>("MeetingPlace")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("MeetingPlot")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.HasKey("MeetingId");

                    b.ToTable("Meetings");
                });

            modelBuilder.Entity("CompanyManagement.Entity.MeetingHasCompanyOwner", b =>
                {
                    b.Property<int>("MeetingHasCompanyOwnerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CompanyOwnerId")
                        .HasColumnType("int");

                    b.Property<int>("MeetingId")
                        .HasColumnType("int");

                    b.HasKey("MeetingHasCompanyOwnerId");

                    b.HasIndex("CompanyOwnerId");

                    b.HasIndex("MeetingId");

                    b.ToTable("MeetingHasCompanyOwners");
                });

            modelBuilder.Entity("CompanyManagement.Entity.MeetingHasEmployee", b =>
                {
                    b.Property<int>("MeetingHasEmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("MeetingId")
                        .HasColumnType("int");

                    b.HasKey("MeetingHasEmployeeId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("MeetingId");

                    b.ToTable("MeetingHasEmployees");
                });

            modelBuilder.Entity("CompanyManagement.Entity.PaymentType", b =>
                {
                    b.Property<int>("PaymentTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PaymentTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("PaymentTypeId");

                    b.ToTable("PaymentTypes");
                });

            modelBuilder.Entity("CompanyManagement.Entity.ProductOrService", b =>
                {
                    b.Property<int>("ProductOrServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsProductOrService")
                        .HasColumnType("bit");

                    b.Property<string>("ProductOrServiceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<int>("ProductOrServiceTypeId")
                        .HasColumnType("int");

                    b.HasKey("ProductOrServiceId");

                    b.HasIndex("ProductOrServiceTypeId");

                    b.ToTable("ProductsOrServices");
                });

            modelBuilder.Entity("CompanyManagement.Entity.ProductOrServiceType", b =>
                {
                    b.Property<int>("ProductOrServiceTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ProductOrServiceTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("ProductOrServiceTypeId");

                    b.ToTable("ProductOrServiceTypes");
                });

            modelBuilder.Entity("CompanyManagement.Entity.ProfessionType", b =>
                {
                    b.Property<int>("ProfessionTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ProfessionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("ProfessionTypeId");

                    b.ToTable("ProfessionTypes");
                });

            modelBuilder.Entity("CompanyManagement.Entity.Task", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DaysPassedToComplete")
                        .HasColumnType("int");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("TaskBeginningDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TaskDetails")
                        .HasColumnType("nvarchar(1000)")
                        .HasMaxLength(1000);

                    b.Property<DateTime?>("TaskFinishDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.HasKey("TaskId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("CompanyManagement.Entity.TaskHasCompanyOwner", b =>
                {
                    b.Property<int>("TaskHasCompanyOwnerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CompanyOwnerId")
                        .HasColumnType("int");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.HasKey("TaskHasCompanyOwnerId");

                    b.HasIndex("CompanyOwnerId");

                    b.HasIndex("TaskId");

                    b.ToTable("TaskHasCompanyOwners");
                });

            modelBuilder.Entity("CompanyManagement.Entity.TaskHasEmployee", b =>
                {
                    b.Property<int>("TaskHasEmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.HasKey("TaskHasEmployeeId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("TaskId");

                    b.ToTable("TaskHasEmployees");
                });

            modelBuilder.Entity("CompanyManagement.Entity.Company", b =>
                {
                    b.HasOne("CompanyManagement.Entity.CompanyType", "CompanyType")
                        .WithMany("Companies")
                        .HasForeignKey("CompanyTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CompanyManagement.Entity.CompanyGivesBonusToEmployee", b =>
                {
                    b.HasOne("CompanyManagement.Entity.Company", "Company")
                        .WithMany("CompanyGivesBonusToEmployees")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CompanyManagement.Entity.Employee", "Employee")
                        .WithMany("CompanyGivesBonusToEmployees")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CompanyManagement.Entity.CompanyHasDepartmentType", b =>
                {
                    b.HasOne("CompanyManagement.Entity.Company", "Company")
                        .WithMany("CompanyHasDepartmentTypes")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CompanyManagement.Entity.DepartmentType", "DepartmentType")
                        .WithMany("CompanyHasDepartmentTypes")
                        .HasForeignKey("DepartmentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CompanyManagement.Entity.CompanyHasProductOrService", b =>
                {
                    b.HasOne("CompanyManagement.Entity.Company", "Company")
                        .WithMany("CompanyHasProductOrServices")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CompanyManagement.Entity.ProductOrService", "ProductOrService")
                        .WithMany("CompanyHasProductOrServices")
                        .HasForeignKey("ProductOrServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CompanyManagement.Entity.CompanyOwnerHasCompany", b =>
                {
                    b.HasOne("CompanyManagement.Entity.Company", "Company")
                        .WithMany("CompanyOwnerHasCompanies")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CompanyManagement.Entity.CompanyOwner", "CompanyOwner")
                        .WithMany("CompanyOwnerHasCompanies")
                        .HasForeignKey("CompanyOwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CompanyManagement.Entity.CustomerBuysCompanyHasProductOrService", b =>
                {
                    b.HasOne("CompanyManagement.Entity.CompanyHasProductOrService", "CompanyHasProductOrService")
                        .WithMany("CustomerBuysCompanyHasProductOrServices")
                        .HasForeignKey("CompanyHasProductOrServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CompanyManagement.Entity.Customer", "Customer")
                        .WithMany("CustomerBuysCompanyHasProductOrServices")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CompanyManagement.Entity.PaymentType", "PaymentType")
                        .WithMany("CustomerBuysCompanyHasProductOrServices")
                        .HasForeignKey("PaymentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CompanyManagement.Entity.Employee", b =>
                {
                    b.HasOne("CompanyManagement.Entity.ProfessionType", "ProfessionType")
                        .WithMany("Employees")
                        .HasForeignKey("EmployeeProfessionTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CompanyManagement.Entity.EmployeeHasCompanyHasDepartmentType", b =>
                {
                    b.HasOne("CompanyManagement.Entity.CompanyHasDepartmentType", "CompanyHasDepartmentType")
                        .WithMany("EmployeeHasCompanyHasDepartmentTypes")
                        .HasForeignKey("CompanyHasDepartmentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CompanyManagement.Entity.Company", null)
                        .WithMany("EmployeeHasCompanyHasDepartmentTypes")
                        .HasForeignKey("CompanyId");

                    b.HasOne("CompanyManagement.Entity.Employee", "Employee")
                        .WithMany("EmployeeHasCompanies")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CompanyManagement.Entity.MeetingHasCompanyOwner", b =>
                {
                    b.HasOne("CompanyManagement.Entity.CompanyOwner", "CompanyOwner")
                        .WithMany("MeetingHasCompanyOwners")
                        .HasForeignKey("CompanyOwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CompanyManagement.Entity.Meeting", "Meeting")
                        .WithMany("MeetingHasCompanyOwners")
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CompanyManagement.Entity.MeetingHasEmployee", b =>
                {
                    b.HasOne("CompanyManagement.Entity.Employee", "Employee")
                        .WithMany("MeetingHasEmployees")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CompanyManagement.Entity.Meeting", "Meeting")
                        .WithMany("MeetingHasEmployees")
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CompanyManagement.Entity.ProductOrService", b =>
                {
                    b.HasOne("CompanyManagement.Entity.ProductOrServiceType", "ProductOrServiceType")
                        .WithMany("ProductsOrServices")
                        .HasForeignKey("ProductOrServiceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CompanyManagement.Entity.TaskHasCompanyOwner", b =>
                {
                    b.HasOne("CompanyManagement.Entity.CompanyOwner", "CompanyOwner")
                        .WithMany("TaskHasCompanyOwners")
                        .HasForeignKey("CompanyOwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CompanyManagement.Entity.Task", "Task")
                        .WithMany("TaskHasCompanyOwners")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CompanyManagement.Entity.TaskHasEmployee", b =>
                {
                    b.HasOne("CompanyManagement.Entity.Employee", "Employee")
                        .WithMany("TaskHasEmployees")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CompanyManagement.Entity.Task", "Task")
                        .WithMany("TaskHasEmployees")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
